config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/users/:id/settings' => 'users#settings', as: :account_settings

  get '/auth/facebook/callback' => 'sessions#facebook_callback'


  resources :books do
    resources :reflections, only: [:new, :edit, :show]
  end

  resources :users
  resources :books
  resources :reflections

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one_attached :image
  has_many :reflections, foreign_key: :reflection_book_id
  has_many :reflection_users, through: :reflections
  belongs_to :owner_user, class_name: "User", optional: true

  validates :title, presence: { message: "You must enter a book title." }
  validates :author, presence: { message: "You must enter the author's name of the book." }
  validates :image, presence: { message: "Please upload an image of the book cover." }


  accepts_nested_attributes_for :reflections




end

app/models/reflection.rb
class Reflection < ActiveRecord::Base
  belongs_to :reflection_user, class_name: "User"
  belongs_to :reflection_book, class_name: "Book"

  validates :title, presence: { message: "Don't be afraid to add an eye-catching title." }
  validates :content, presence: { message: "Don't be afraid to write a reflection. (1000 characters max)" }, length: { maximum: 1000, message: "Express yourself within 1000 characters."}

  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :owned_books, foreign_key: :owner_user_id, class_name: "Book"
  has_many :reflections, foreign_key: :reflection_user_id
  has_many :reflection_books, through: :reflections

  validates :username, presence: { message: "You must enter a username."}, uniqueness: { message: "This username already exists. Please try another."}
  validates :email, presence: { message: "You must enter a valid email."}, uniqueness: { message: "This email has already been taken. Please try another."}
  validates :password, presence: { message: "You must enter a password."}, length: { :within => 8..40, message: "Your password must be a minimum of 8 characters." }

  scope :with_reflections, ->{ joins(:reflections).order(created_at: :DESC) }



  has_secure_password validations: false







end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def require_login
    return redirect_to root_path unless current_user
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login
  before_action :set_book, only: [:edit, :update, :show, :destroy]

  def index
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    @book.owner_user = current_user
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def show
  end

  def edit
    if current_user == @book.owner_user
      @book
    else
      redirect_to book_path(@book)
    end
  end

  def update
      if @book.update_attributes(book_params)
       redirect_to book_path(@book)
      else
       render :edit
      end
  end

  def destroy
   if current_user == @book.owner_user
      @book.destroy
      redirect_to user_path(@book.owner_user)
   end
 end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :image)
  end

end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :require_login
  before_action :set_reflection, only: [:edit, :update, :show, :destroy]

  def new
    @book = Book.find(params[:book_id])
    if current_user == @book.owner_user
      @reflection = @book.reflections.build
    else
      redirect_to users_path(current_user)
    end
  end

  def create
    @reflection = Reflection.create(reflection_params)
    @reflection.reflection_user = current_user
    if @reflection.save
      redirect_to book_reflection_path(@reflection.reflection_book, @reflection)
    else
      @book = @reflection.reflection_book
      render :new
    end
  end

  def show
    if current_user == @reflection.reflection_user
      @book = @reflection.reflection_book
    else
      redirect_to book_path(@reflection.reflection_book)
    end
  end

  def edit
    if current_user == @reflection.reflection_user
      @reflection.reflection_book
    else
      redirect_to book_reflection_path(@reflection.reflection_book, @reflection)
    end
  end

  def update
      if @reflection.update_attributes(reflection_params)
       redirect_to book_reflection_path(@reflection.reflection_book, @reflection)
      else
       render :edit
      end
  end

  def destroy
   if current_user == @reflection.reflection_user
      @reflection.destroy
      redirect_to user_path(@reflection.reflection_user)
   end
 end

  private

  def set_reflection
    @reflection = Reflection.find(params[:id])
  end

  def reflection_params
    params.require(:reflection).permit(:title, :content, :reflection_book_id, :reflection_user_id)
  end

end

app/controllers/sessions_controller.rb
require 'securerandom'

class SessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    if User.find_by(username: params[:username])
      @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to users_path
          return
       else
         @user.errors.add(:password, "Invalid password!")
       end
    end
    render :new
  end

  def facebook_callback
    secure_password = SecureRandom.hex(16)
    @user = User.find_or_create_by(username: auth['info']['name']) do | u |
      u.email = auth['info']['email']
      u.password = secure_password
    end
      if @user.save || @user.id
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render :new
      end
    end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :home]
  before_action :set_user, only: [:show, :edit, :settings, :destroy]

  def home
    if session[:user_id]
      redirect_to users_path
    end
  end

  def index
    @users = User.with_reflections
  end


  def new
    if !session[:user_id]
      @user = User.new
    else
      redirect_to users_path(@user)
    end
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @books = @user.owned_books
  end

  def settings
    access_self
  end

  def edit
    access_self
  end

  def update
    if @user = current_user
      if @user.update_attributes(user_params)
       redirect_to account_settings_path(@user.id)
      else
       render :edit
      end
    end
  end

  def destroy
   if current_user.id == @user.id
      @user.destroy
      session.delete :user_id
      redirect_to root_path
   end
 end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def access_self
    if @user = current_user
      @user
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  

end

app/helpers/book_helper.rb
module BookHelper

  def created(book)
    book.created_at.strftime("%d %B %Y")
  end

end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/profile.css">
  </head>
  <body>
    <%= render "users/banner" %>
    
    <div class="home-div">

      <div class="ayb">EDIT YOUR BOOK</div>

      <div class="nb-errors">
        <%= render partial: "layouts/form_errors", locals: { object: @book } %>
      </div>


      <%= render partial: "layouts/book_form", locals: { text: "Update Book" } %>

        </div>

      </body>
    </html>

app/views/books/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/newbook.css">
  </head>
  <body>
    <%= render "users/banner" %>
    
    <div class="home-div">

      <div class="ayb">ADD YOUR BOOK</div>

      <div class="nb-errors">
       <%= render partial: "layouts/form_errors", locals: { object: @book } %>
      </div>

      <%= render partial: "layouts/book_form", locals: { text: "Create Book" } %>

        </div>

      </body>
    </html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/books.css">
  </head>
  <body>
    <%= render "users/banner" %>

    <div class="home-div">
     <div class="btac">
      <%= @book.title %>
      <br>
      <div class="bauthor"><%= @book.author %></div>
      <% if @book.image.attached? %>
      <div class="bookcover">
        <img src="<%=(url_for(@book.image))%>">
      </div>
      </div>
        <% if @book.owner_user == current_user %>
          <%= button_to "Edit Book", edit_book_path(@book), method: :get, class: "eb-button" %>
          <%= button_to "Delete Book", book_path(@book), method: :delete, class: "db-button" %>
        <% end %>
      <% end %>
      </div>
      <br>
      </br>
    <div class="reflections" style="float:right; width:500px; height:500px; overflow:auto;">
      <% @book.reflections.each do | r | %>
        <div class="book-title" style = "text-transform:uppercase;">
          <%= r.title %>
        </div>
        <br>
        <br>
        <%= r.content %>
        <br>
        <div class="bsb-buttons">
          <%= render partial: "layouts/edit_delete_reflections", locals: { object: @book, obj: r } %>
        </div>
        <br>
        </br>
        <br>
        </br>
      <% end %>
      <div class="wr-button-div">
      <% if @book.owner_user == current_user %>
        <%= button_to "Write a reflection", new_book_reflection_path(@book), method: :get, class: "wr-button" %>
      <% end %>
      </div>


          </div>

      </body>
    </html>

app/views/layouts/_book_form.html.erb
<%= form_for @book do | f | %>
<div class="book-input">
  <%= f.text_field :title, placeholder: "Book Title:" %>
  <br>
  </br>
  <%= f.text_field :author, placeholder: "Book Author:" %>
  </div>
  <br>
  </br>
  <div class="upload-button"><%= f.file_field :image %></div>
  <br>
  <br>
  </br>
 <button class="create-book-button"><%= f.submit text %></button>
<% end %>

app/views/layouts/_edit_delete_reflections.html.erb
<% if object.owner_user == current_user %>
  <%= button_to "Edit Reflection", edit_reflection_path(obj), method: :get, class: "bre-button" %>
  <%= button_to "Delete Reflection", reflection_path(obj), method: :delete, class: "brd-button" %>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.messages.values.each do | msg | %>
     <% msg.each do | m | %>
       <%= m %>
     <br>
     <% end %>
  <% end %>
<% end %>

app/views/layouts/_user_form.html.erb
<%= form_for object do | f | %>

<div class="username-edit"><svg class="svg-icon" fill="#999" viewBox="0 0 20 20">
        <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
      </svg><%= f.text_field :username, placeholder: "Username" %></div>
<br>
<div class="email-edit"><svg class="svg-icon" fill="#999" viewBox="0 0 20 20">
        <path d="M17.388,4.751H2.613c-0.213,0-0.389,0.175-0.389,0.389v9.72c0,0.216,0.175,0.389,0.389,0.389h14.775c0.214,0,0.389-0.173,0.389-0.389v-9.72C17.776,4.926,17.602,4.751,17.388,4.751 M16.448,5.53L10,11.984L3.552,5.53H16.448zM3.002,6.081l3.921,3.925l-3.921,3.925V6.081z M3.56,14.471l3.914-3.916l2.253,2.253c0.153,0.153,0.395,0.153,0.548,0l2.253-2.253l3.913,3.916H3.56z M16.999,13.931l-3.921-3.925l3.921-3.925V13.931z"></path>
      </svg><%= f.email_field :email, placeholder: "Email" %></div>
<br>
<div class="password-edit"><svg class="svg-icon" fill="#999" viewBox="0 0 20 20">
        <path d="M17.308,7.564h-1.993c0-2.929-2.385-5.314-5.314-5.314S4.686,4.635,4.686,7.564H2.693c-0.244,0-0.443,0.2-0.443,0.443v9.3c0,0.243,0.199,0.442,0.443,0.442h14.615c0.243,0,0.442-0.199,0.442-0.442v-9.3C17.75,7.764,17.551,7.564,17.308,7.564 M10,3.136c2.442,0,4.43,1.986,4.43,4.428H5.571C5.571,5.122,7.558,3.136,10,3.136 M16.865,16.864H3.136V8.45h13.729V16.864z M10,10.664c-0.854,0-1.55,0.696-1.55,1.551c0,0.699,0.467,1.292,1.107,1.485v0.95c0,0.243,0.2,0.442,0.443,0.442s0.443-0.199,0.443-0.442V13.7c0.64-0.193,1.106-0.786,1.106-1.485C11.55,11.36,10.854,10.664,10,10.664 M10,12.878c-0.366,0-0.664-0.298-0.664-0.663c0-0.366,0.298-0.665,0.664-0.665c0.365,0,0.664,0.299,0.664,0.665C10.664,12.58,10.365,12.878,10,12.878"></path>
      </svg><%= f.password_field :password, placeholder: "Password" %></div>
      <br>
       <button class="sign-up-button"><%= f.submit text %></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reflections/_form.html.erb
<%= form_for @reflection do | f | %>
  <%= f.hidden_field :reflection_book_id %>

  <div class="nb-errors">
    <%= render partial: "layouts/form_errors", locals: { object: @reflection } %>
  </div>

 <div class="book-input">
  <%= f.text_field :title, placeholder: "Reflection Title:" %>
  <br>
  <br>
  <%= f.text_area :content, placeholder: "Free your reflection here...", class: "nr-ta" %>
  <br>
  </div>

  <button class="create-book-button"><%= f.submit "Reflect" %></button>

<% end %>

app/views/reflections/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/profile.css">
  </head>
  <body>
    <%= render "users/banner" %>
    <div class="home-div">

      <div class="rn-bta">
        <%= @reflection.reflection_book.title %><br>
        <%= @reflection.reflection_book.author %>
      </div>
        <br>
        <br>
      <%= render "form" %>

        </div>

      </body>
    </html>

app/views/reflections/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/newreflection.css">
  </head>
  <body>
    <%= render "users/banner" %>
    <div class="home-div">

    <div class="rn-bta">
      <%= @book.title %><br>
      <%= @book.author %>
    </div>
      <br>
      <br>
      <div class="nr-form">
        <%= render "form" %>
      </div>
        </div>

      </body>
    </html>

app/views/reflections/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/profile.css">
  </head>
  <body>
    <%= render "users/banner" %>

    <div class="home-div">
     <div class="btac"><%= link_to book_path(@book) do %>
      <div class="btrsp">
      <%= @book.title %>
        <br>
         <%= @book.author %>
        </div>
         <br>
          <img src="<%=(url_for(@book.image))%>">
          <% end %>
         <br>
        </br>
       </div>
    </div>



      <div class="reflections-show" style="float:right; width:500px; height:500px; overflow:auto;">
      <div class="book-title" style = "text-transform:uppercase;">
      <%= @reflection.title %>
      </div>
      <br>
      <br>
      <%= @reflection.content %>
      <br>
      <div class="rshow-button"><%= render partial: "layouts/edit_delete_reflections", locals: { object: @book, obj: @reflection } %></div>


        </div>


      </body>
    </html>

app/views/users/_banner.html.erb
<div class="header">
  <div class="banner-logo"><img src="/assets/Reflections_Logo.png"></div>
  <div class="header-right">
    <%= link_to "HOME", users_path %>
    <%= link_to "ADD BOOK", new_book_path %>
    <%= link_to "PROFILE", user_path(current_user.id) %>
    <%= link_to "ACCOUNT SETTINGS", account_settings_path(current_user.id) %>
  </div>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/edit-user.css">
  </head>
  <body>
    <%= render "banner" %>
      <div class="edit-errors">
        <%= render partial: "layouts/form_errors", locals: { object: @user } %>
      </div>

       <div class="edit-section-div">
        <br>
        </br>
         <br>
         </br>
       <div class="eyd-title"><h1>EDIT YOUR DETAILS</h1></div>
         <br>
        <br>
       </br>
     <div class="fields">

      <%= render partial: "layouts/user_form", locals: { object: @user, text: "Update Account" } %>

        </div>
      </div>

      </body>
    </html>

app/views/users/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/main.css">
  </head>
  <body>
    <style>
     body {
       background-image: url("/assets/Background.png");
       background-repeat: no-repeat;
       background-attachment: fixed;
       background-size: cover;
      }
    </style>
    <div class="main-div">
      <a href="/">
        <img class="logo-main" border="0"  src="/assets/Reflections_Logo.png">
      </a>
      <br>
      <br>
      </br>
      <div class="welcome">WELCOME TO <b>REFLECTIONS</b></div>
      <div class="main-welcome">
        <p>
        Giving you the oppurtunity to write down your <i>reflective</i> insights into the most wonderful and inspiring books.
        <br></br>
        <em>"Let your words be the mirror to your mind."</em>
        </p>
      </div>
      <br>

        <%= button_to("Log In", login_path, class: "login-button") %>
        <br></br>
        <%= button_to("Sign Up", new_user_path, method: :get, class: "signup-button") %>

   </div>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/home.css">
  </head>
  <body>
    <%= render "banner" %>

    <div class="scrolling-wrapper">
      <% @users.each do | user | %>
        <div class="index-page"><%= link_to user_path(user) do %>
          <div class="card-home">
            <div class="text">
           <h1><%= user.username %></h1>
            <% user.owned_books.each do | b | %>
             <br>
              <p><%= b.title %></p>
              <% end %>
              </div>
             </div>
            <% end %>
           </div>
          <% end %>
        </div>




      </body>
    </html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/signup.css">
  </head>
  <body>
    <style>
     body {
       background-image: url("/assets/Background.png");
       background-repeat: no-repeat;
       background-attachment: fixed;
       background-size: cover;
      }
    </style>

    <div class="signup-errors">
      <%= render partial: "layouts/form_errors", locals: { object: @user } %>
    </div>

    <div class="login-div">
      <a href="/">
        <img class="logo" border="0"  src="/assets/Reflections_Logo.png">
      </a>
    <div class="login-title">CREATE YOUR ACCOUNT</div>
    <div class="fields">

      <%= render partial: "layouts/user_form", locals: { object: @user, text: "Create Account" } %>

      <div class="link">
         Already have a Reflection account? <%= link_to "Login", login_path%>
      </div>
      </div>

   </div>
  </body>
</html>

app/views/users/settings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/books.css">
  </head>
  <body>
    <%= render "banner" %>
    
    <div class="home-div">

      <div class="settings-name"><%= @user.username %></div>
      <br></br>
      <br></br>
      <%= button_to("Log out", logout_path, method: :delete, class: "logout-button") %>
      <br></br>
      <%= button_to("Edit Profile", edit_user_path(@user), method: :get, class: "ep-button") %>
      <br></br>
      <%= button_to("Delete Account", user_path(current_user), method: :delete, class: "da-button") %>


        </div>

      </body>
    </html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/profile.css">
  </head>
  <body>
    <%= render "banner" %>

    <div class="profile-un"><%= @user.username %></div>
    <br>

       <div class="profile-container">
        <% @books.each do | book | %>
          <div class="link-to" id="htitle"><%= link_to book_path(book) do %>
             <div class="card">
              <div class="card-image"><img src="<%=(url_for(book.image))%>"></div>
                <div class="card-text">
                  <span class="date"></span>
                  <h2><%= book.title %></h2>
                  <% book.reflections.limit(1).each do | r |%>
                  <br>
                  <p><%= r.title %></p>
                  <br>
                 <% end %>
                </div>
               <div class="card-stats">
              <div class="stat">
             <div class="value"><p> <%= created(book) %> </p></div>
            </div>
           </div>
         </div>
       <% end %>
      </div>
    <% end %>
   </div>

  </body>
</html>